/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exerciciosTelaJava;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class TelaCadastroSimples extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroSimples
     */
    public TelaCadastroSimples() {
        initComponents(); 
        varcombo.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        varNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        varCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        varSNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        varIdade = new javax.swing.JTextField();
        varCEP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ConcluirCadastro = new javax.swing.JToggleButton();
        varcombo = new javax.swing.JComboBox<>();
        varVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        varNome1 = new javax.swing.JTextField();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CadatroSimplesdePessoa");
        setBackground(new java.awt.Color(51, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(442360, 442360));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("CEP:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 220, 80, 30);

        varNome.setText("digite Telefone...");
        varNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNomeActionPerformed(evt);
            }
        });
        getContentPane().add(varNome);
        varNome.setBounds(580, 120, 240, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 51));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel3.setText("Tela Cadastro Pessoa");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 0, 270, 50);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Sobre nome: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 90, 120, 40);

        varCPF.setText("digite CPF...");
        varCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varCPFActionPerformed(evt);
            }
        });
        getContentPane().add(varCPF);
        varCPF.setBounds(190, 140, 230, 30);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("CPF:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 140, 80, 30);

        varSNome.setText("digite sobre nome..");
        getContentPane().add(varSNome);
        varSNome.setBounds(190, 100, 230, 30);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("idade:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 180, 80, 30);

        varIdade.setText("digite idade...");
        varIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(varIdade);
        varIdade.setBounds(190, 180, 230, 30);

        varCEP.setText("digite CEP..");
        varCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varCEPActionPerformed(evt);
            }
        });
        getContentPane().add(varCEP);
        varCEP.setBounds(190, 220, 230, 30);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("nome: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 60, 80, 30);

        ConcluirCadastro.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ConcluirCadastro.setText("Cadastrar");
        ConcluirCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConcluirCadastroMouseClicked(evt);
            }
        });
        ConcluirCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcluirCadastroActionPerformed(evt);
            }
        });
        ConcluirCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ConcluirCadastroKeyPressed(evt);
            }
        });
        getContentPane().add(ConcluirCadastro);
        ConcluirCadastro.setBounds(420, 330, 120, 30);

        varcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "usuário comum", "administrador", "convidado." }));
        getContentPane().add(varcombo);
        varcombo.setBounds(250, 290, 230, 30);

        varVoltar.setText("Voltar");
        varVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(varVoltar);
        varVoltar.setBounds(200, 330, 110, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Escolha seu Usuario:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 290, 190, 30);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("TEL. Contato:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 120, 140, 24);

        varNome1.setText("digite nome...");
        varNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNome1ActionPerformed(evt);
            }
        });
        getContentPane().add(varNome1);
        varNome1.setBounds(190, 60, 230, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void varNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varNomeActionPerformed

    private void varCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varCEPActionPerformed

    private void ConcluirCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConcluirCadastroActionPerformed
      JOptionPane.showMessageDialog(null,"DADOS DIGITADOS DA PESSOA \n"+
                                                     "****************************"+
                                                     "NOME :"+varNome.getText()+"\n"+
                                                     "SobreNome:"+varSNome.getText()+"\n"+
                                                     "CPF:"+varCPF.getText()+"\n+"+
                                                     "IDADE:"+varIdade.getText()+"\n+"+
                                                     "CEP:"+varCEP.getText()+"\n+"+
                                                     "USUÁRIO:"+varcombo.getSelectedItem().toString() );
                                                 
      varNome.setText("");
      varSNome.setText("");
      varCPF.setText("");
      varIdade.setText("");
      varCEP.setText("");
      varcombo.setSelectedIndex(-1);
      
    }//GEN-LAST:event_ConcluirCadastroActionPerformed

    private void varIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varIdadeActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void ConcluirCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConcluirCadastroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ConcluirCadastroMouseClicked

    private void ConcluirCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConcluirCadastroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConcluirCadastroKeyPressed

    private void varCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varCPFActionPerformed

    private void varVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varVoltarActionPerformed

    private void varNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varNome1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroSimples().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ConcluirCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField varCEP;
    private javax.swing.JTextField varCPF;
    private javax.swing.JTextField varIdade;
    private javax.swing.JTextField varNome;
    private javax.swing.JTextField varNome1;
    private javax.swing.JTextField varSNome;
    private javax.swing.JButton varVoltar;
    private javax.swing.JComboBox<String> varcombo;
    // End of variables declaration//GEN-END:variables
}
